# Generated by Django 4.0.1 on 2022-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('users', '0001_initial'), ('users', '0002_alter_location_lat_alter_location_lng')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('role', models.CharField(
                    choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')],
                    default='member', max_length=9, verbose_name='Роль пользователя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('location', models.ManyToManyField(to='users.Location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
        ),
    ]
